# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160907_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
