# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160907_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
